#!/bin/sh -e

./configure \
    --prefix=/usr \
    --with-modules \
    --with-xft \
    --with-x-toolkit=athena \
    --without-toolkit-scroll-bars \
    --without-dbus \
    --without-gconf \
    --without-gsettings

mkdir -p "$1/usr/share/emacs/site-lisp"
cat << EOF > "$1/usr/share/emacs/site-lisp/site-start.el"
;; fix ugly
(menu-bar-mode -1)
(tool-bar-mode -1)
(scroll-bar-mode -1)
(horizontal-scroll-bar-mode -1)
EOF

make
make DESTDIR="$1" install
