#!/bin/sh -e

export GOFLAGS="-buildmode=pie -mod=vendor -trimpath"
export CGO_LDFLAGS="$LDFLAGS"
go build -o go-md2man .
./go-md2man -in=go-md2man.1.md -out=go-md2man.1

install -Dm755 go-md2man "$pkgdir/usr/bin/go-md2man"
install -Dm755 go-md2man.1 "$pkgdir/usr/share/man/man1/go-md2man.1"
install -Dm755 LICENSE.md "$pkgdir/usr/share/licenses/$pkgname/LICENSE"

