#!/bin/sh -e

# Change the order for checking installed compilers as
# the ccache clang symlink might exist, but clang might not be installed.
sed -i 's/clang gcc cc/cc clang gcc/g'       source/configure
sed -i 's/clang++ g++ c++/c++ clang++ g++/g' source/configure

source/configure \
    --prefix=/usr \
    --sbindir=/usr/bin

make
make DESTDIR="$1" install
