#!/bin/sh -e

# ccache is causing the issue to expect clang instead of gcc.
# Just disable it.
export CC="${CC:-/usr/bin/cc}"
export CXX="${CXX:-/usr/bin/c++}"

source/configure \
    --prefix=/usr \
    --sbindir=/usr/bin

make
make DESTDIR="$1" install
