#!/bin/sh -e

export DESTDIR="$1"

sed -i 's/tinfo.a//' CMakeLists.txt
sed -i 's/tinfo//'   CMakeLists.txt

cmake -B build \
   -DCMAKE_INSTALL_PREFIX=/usr \
   -DCMAKE_BUILD_TYPE=Release \
   -DISPC_INCLUDE_EXAMPLES=OFF \
   -DISPC_INCLUDE_TESTS=OFF \
   -DISPC_NO_DUMPS=ON \
   -DARM_ENABLED=OFF

cmake --build build
cmake --install build
