#!/bin/sh -e

patch -p1 < f3aa4b156360ce4a18e4a3897f883b663771ba24.patch

sed -i \
    -e "/^CFLAGS/s/=/= $CFLAGS -static/" \
    -e "/^LDFLAGS/s/=/= $LDFLAGS -static/" \
    config.mk

make ubase-box
make DESTDIR="$1" PREFIX=/usr ubase-box-install

# Remove 'su' which doesn't support '-c'.
unlink "$1/usr/bin/su"
unlink "$1/usr/bin/stat"
