#!/bin/sh -e

export CFLAGS="$CFLAGS -std=gnu99"

./configure \
	--prefix=/usr \
	--sysconfdir=/etc \
	--mandir=/usr/share/man \
	--infodir=/usr/share/info \
	--localstatedir=/var

make

make DESTDIR="$1" install
