#!/bin/sh -e

./configure --prefix=/usr \
            --sbindir=/usr/bin \
            --libexecdir=/usr/lib/gnupg \
            --disable-gnutls \
            --enable-symcryptrun \
            --enable-gpg-is-gpg2 \
            --disable-ldap \
            --disable-nls

make
make DESTDIR="$1" install

ln -s /usr/bin/gpg2 "$1/usr/bin/gpg"
ln -s /usr/bin/gpgv2 "$1/usr/bin/gpgv"
