#!/bin/sh -e

./configure --prefix=/usr \
            --sbindir=/usr/bin \
            --libexecdir=/usr/lib/gnupg \
            --enable-symcryptrun \
            --disable-ldap \
            --disable-nls

make
make DESTDIR="$1" install
