#!/bin/sh -e

# fake
export MAKEINFO=true
touch fig2dev convert ; chmod +x fig2dev convert
export PATH=$PWD:$PATH

autoreconf

./configure --prefix=/usr \
            --sbindir=/usr/bin \
            --libexecdir=/usr/lib/gnupg \
            --enable-maintainer-mode \
            --enable-symcryptrun

make DESTDIR="$1" install

# fix gnupg1/gnupg2 conflict
mv "$1/usr/bin/gpg" "$1/usr/bin/gpg2"
mv "$1/usr/bin/gpgv" "$1/usr/bin/gpgv2"
