#!/bin/sh

printf "==============================

Make your voice heard in the future of KISS! Participate in the BDFL survey.

https://kiss-poll.armaanb.net

Form closes 2021-02-24.

==============================\n"
