#!/bin/sh

printf "+-----------------------------------------------------+
| ATTENTION KISS USERS                     2021-02-23 |
+-----------------------------------------------------+
| The BDFL poll was shut down early due to a lack of  |
| meaningful participation.                           |
|                                                     |
| Because of this, kiss-community is now proud to     |
| declare Dilyn Corner as the new KISS BDFL!          |
|                                                     |
| A summary of the poll results is here:              |
| https://i.imgur.com/7fudIqe.png                     |
|                                                     |
| A blog post and more offical announcements will     |
| follow soon.                                        |
+-----------------------------------------------------+\n"
