#!/bin/sh -e

# 'cmake' doesn't create the directory.
mkdir -p "$1/build"
cd "$1/build"

cmake .. -DUTF8_TESTS=Off -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr

make
make DESTDIR="$1" install
