#!/bin/sh -e

cat <<EOF
NOTE: The 'libXslt' package has been renamed to 'libxslt'. 'libxslt' must be \
built and this stub package be removed by running the following command:
'kiss b libxslt && KISS_FORCE=1 kiss r libXslt'
EOF
