#!/bin/sh -e

cat <<EOF

NOTE: A menu system has to be installed. Possible choices:

- fzf
- dmenu (external menu)
- rofi (external menu)

External menus must be called with 'ytfzf -D'.

Optional: ueberzug can be installed with 'pip'
to get thumbnails support.


NOTE: if mpv fails to play the video, it needs to be
rebuilt. 

EOF
