#!/bin/sh -e

cd runit-2.1.2

(
cd src

sed -e 's@sbin/runit@usr/bin/runit@g' -i runit.h
printf '%s -D_GNU_SOURCE -static\n' "${CC-cc}" "$CFLAGS" > conf-cc
printf '%s %s -static -Wl,-z -Wl,noexecstack\n' "${CC-cc}" "$CFLAGS" > conf-ld
sed -i -e 's:^char \*varservice ="/service/";$:char \*varservice ="/var/service/";:' sv.c

make

for bin in chpst runit runit-init runsv runsvchdir runsvdir sv svlogd utmpset; do
    install -Dm755 "$bin" "$1/usr/bin/$bin"
done
)

(
cd man
for man in ./*; do
    install -Dm644 "$man" "$1/usr/share/man/man8/$man"
done
)


mkdir -p "$1/var/service"
ln -s runit-init "$1/usr/bin/init"

# Link to the default init scripts
mkdir -p "$1/etc/runit"

# I have added a post-install for this at the moment
# see <https://github.com/kisslinux/kiss/issues/112>
# ln -s /usr/lib/init/rc.boot "$1/etc/runit/1"
# ln -s /usr/lib/init/rc.shutdown "$1/etc/runit/3"

install -Dm755 ../2 "$1/etc/runit/2"
