#!/bin/sh -e

export DESTDIR="$1"

patch -p1 < libressl.patch
patch -p1 < bitmap-endian.patch

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR=/usr/lib \
    -DCMAKE_BUILD_TYPE=Release

cmake --build   build
cmake --install build
