#!/bin/sh -e

# Remove mandatory gettext dependency.
sed -i 's/^/#/' src/nvim/po/CMakeLists.txt

make \
    CMAKE_BUILD_TYPE=Release \
    CMAKE_INSTALL_PREFIX=/usr \
    CMAKE_INSTALL_LIBDIR=lib \
    -Wno-dev

make DESTDIR="$1" install
