#!/bin/sh -e

sed -i 's/--relative//' utils/install_helper.sh

export DESTDIR="$1"

meson \
    --prefix=/usr \
    -Dexamples=false \
    -Dsbindir=bin \
    . output

ninja -C output
ninja -C output install
