#!/bin/sh -e

export DESTDIR="$1"

cmake -B build \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_LINKER=/usr/bin/lld \
    -DZIG_PREFER_CLANG_CPP_DYLIB=true \
    -DCMAKE_INSTALL_PREFIX=/usr

cmake --build   build
cmake --install build
