#!/bin/sh -e

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --disable-nfsv4 \
    --disable-gss \
    --disable-uuid \
    --sbindir=/usr/bin

sed -i "s|sbindir = /sbin|sbindir = /usr/bin|" ./utils/mount/Makefile

make
make DESTDIR="$1" install
