#!/bin/sh -e

CC="gcc -static" ./configure --prefix=/usr

make

install -Dm755 find/find "$1/usr/bin/gfind"
install -Dm755 xargs/xargs "$1/usr/bin/gxargs"
install -Dm755 locate/locate "$1/usr/bin/locate"
install -Dm755 locate/updatedb "$1/usr/bin/updatedb"
