#!/bin/sh -e

export DESTDIR="$1"

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_BUILD_TYPE=Release

cmake --build   build
cmake --install build

install -Dm644 udev/51-android.rules "$1/etc/udev/rules.d/51-android.rules"
