#!/bin/sh -e

patch -p1 < realpath-workaround.patch

./configure \
    --prefix=/usr \
    --mandir=/usr/share/man \
    --localstatedir=/var \
    --with-priv-mode=none

make
make DESTDIR="$1" install
