#!/bin/sh -e

sed -i '/^\t-install-info/d' makefile

make \
    PREFIX="/usr" \
    LIBS="-lncursesw" \
    build

make DESTDIR="$1" install 

# Remove all doc files.
rm -rf "$1/usr/share/doc"

# Remove all info files.
rm -rf "$1/usr/share/info"
