#!/bin/sh -e

export DESTDIR="$1"

patch -p1 < install.patch
patch -p1 < musl.patch

export LD_LIBRARY_PATH="/usr/lib/llvm/roc/lib:$LD_LIBRARY_PATH"

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_BUILD_TYPE=Release \
	-DUSE_COMGR_LIBRARY=YES \
    -DOPENCL_DIR="$PWD/opencl-runtime"

cmake --build   build
cmake --install build

sed -e "s:$PWD/build:/usr:" -i "$1/usr/lib/cmake/rocclr/ROCclrConfig.cmake"
