#!/bin/sh -e

cargo build --release

install -Dm755 target/release/alacritty "$1/usr/bin/alacritty"

install -Dm644 extra/alacritty.man "$1/usr/share/man/man1/alacritty.1"
install -Dm644 alacritty.yml "$1/usr/share/doc/alacritty/example/alacritty.yml"
