#!/bin/sh -e

./configure \
    --sysconfdir=/etc \
    --prefix=/usr

make
make DESTDIR="$1" install

# Install runit service.
install -Dm755 tor.run         "$1/etc/sv/tor/run"
ln -s /run/runit/supervise.tor "$1/etc/sv/tor/supervise"
