#!/bin/sh -e

for patch in *.patch; do
    patch -p1 < "$patch"
done

# perfetto strikes again
# Probably remove next time chromium gets updated... 
# Broken with gcc 11.1.0
sed -i '/<cstdlib>/a #include <cstdint>' \
    src/3rdparty/chromium/third_party/ots/src/ots.h
sed -i '/<limits>/a #include <cstdint>' \
    src/3rdparty/chromium/third_party/ots/src/gdef.cc
sed -i '/<vector>/a #include <limits>' \
    src/3rdparty/chromium/third_party/perfetto/src/trace_processor/containers/string_pool.h
sed -i '/<array>/a #include <limits>' \
    src/3rdparty/chromium/third_party/abseil-cpp/absl/synchronization/internal/graphcycles.cc
sed -i '/<errno.h>/a #include <string.h>' \
    src/3rdparty/chromium/mojo/public/cpp/platform/named_platform_channel_posix.cc

# Change the version string
sed -i 's/5.15.4/5.15.3/' .qmake.conf

# Remove dbus dependency.
sed -i 's/use_dbus.*/use_dbus=false/' \
    src/3rdparty/chromium/build/config/features.gni

# Disable glibc check
sed -i 's/__GLIBC__ < 2 || __GLIBC_MINOR__ < 17/false/' \
    src/buildtools/configure.json

# Fix some basic things for musl
sed -i 's/nullptr, 0, 0/0, 0, 0/' \
    src/3rdparty/chromium/net/socket/udp_socket_posix.cc

sed -i 's/__GLIBC__/OS_ANDROID/' \
    src/3rdparty/chromium/third_party/crashpad/crashpad/util/linux/thread_info.h

sed -i 's/PPC64)/PPC64 || V8_HOST_ARCH_ARM)/' \
    src/3rdparty/chromium/v8/src/base/cpu.cc

sed -i '/inet.h>/a #include <sys/types.h>' \
    src/3rdparty/chromium/third_party/ots/include/opentype-sanitiser.h

# Remove udev dependency.
sed -i '/use_udev/s/=.*/=false/' \
    src/3rdparty/chromium/build/config/features.gni

sed -i 's/\(use_udev=\)true/\1false/' \
    src/buildtools/config/linux.pri

# Fix nasm hardcoded glibcism
sed -i '/CANONICALIZE_FILE_NAME/d' \
    src/3rdparty/chromium/third_party/nasm/config/config-linux.h

# Remove glibc header.
sed -i '/execinfo.h/d' \
    src/3rdparty/chromium/base/debug/stack_trace_posix.cc

# The build fails if qtwebengine is already installed.
find . -name '*.pr[fio]' | while read -r file; do
    sed -i "s#INCLUDEPATH += #&\$\$QTWEBENGINE_ROOT/include #" "$file"
done

# Increase the limit -- thanks chromium
# shellcheck disable=2039
ulimit -n 4096

qmake QMAKE_CXXFLAGS=-DQT_NO_ACCESSIBILITY -- \
    -feature-webengine-system-zlib \
    -feature-webengine-system-harfbuzz \
    -feature-webengine-system-png \
    -feature-webengine-system-libevent \
    -feature-webengine-system-libvpx \
    -feature-webengine-system-opus \
    -feature-webengine-system-libwebp \
    -feature-webengine-system-ffmpeg \
    -feature-webengine-proprietary-codecs \
    -no-feature-webengine-system-icu \
    -no-feature-webengine-system-glib

make
make INSTALL_ROOT="$1" install
