#!/bin/sh -e

export CC="gcc -static"

export FORCE_UNSAFE_CONFIGURE=1

./configure \
    --prefix=/opt/gnu/coreutils \
    --program-prefix=g \
    --program-transform-name=s/stat/nustat/

make DESTDIR="$1" install
