#!/bin/sh -e

export CFLAGS="$CFLAGS -static"

export FORCE_UNSAFE_CONFIGURE=1

./configure \
    --prefix=/usr \
    --program-prefix=g \
    --program-transform-name=s/stat/nustat/

make
make DESTDIR="$1" install
