#!/bin/sh -e

export DESTDIR="$1"

meson \
    --prefix=/usr \
    -Dtremor=disabled \
    -Dexamples=disabled \
    -Dgtk_doc=disabled \
    -Dcdparanoia=disabled \
    -Dintrospection=disabled \
    -Dsndio=enabled \
    . output

ninja -C output
ninja -C output install
