#!/bin/sh -e

export DESTDIR="$1"

meson \
    --prefix=/usr \
    -Dgl=disabled \
    -Dtests=disabled \
    -Dtremor=disabled \
    -Dexamples=disabled \
    -Dcdparanoia=disabled \
    -Dintrospection=disabled \
    . output

ninja -C output
ninja -C output install
