#!/bin/sh -e

export DESTDIR="$1"

cmake -B build \
    -Wno-dev \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DENABLE_MAN=OFF \
    -DENABLE_DOC=OFF \
    -DENABLE_GNUTLS=ON \
    -DENABLE_SCRIPTS=OFF \
    -DENABLE_SPELL=OFF

cmake --build   build
cmake --install build
