#!/bin/sh -e

export DESTDIR="$1"

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_BUILD_TYPE=Release \
    -DENABLE_PYTHON=OFF \
    -DENABLE_PERL=OFF \
    -DENABLE_PHP=OFF \
    -DENABLE_RUBY=OFF \
    -DENABLE_TCL=OFF \
    -DENABLE_LUA=OFF \
    -DENABLE_GUILE=OFF \
    -DENABLE_SPELL=OFF \
    -DENABLE_MAN=OFF

cmake --build build
cmake --install build
