#!/bin/sh -e

cat <<EOF

NOTE: Plan9 programs are installed to
      /usr/local/plan9/ to avoid conflicts with
      system programs. If you want to be able to
      use Plan9 programs, add /usr/local/plan9/bin
      to your path.

EOF
