#!/bin/sh -e

IFS=. read -r ver1 ver2 _ < "${0%/*}/version"

unix/configure \
    --prefix=/usr \
    --mandir=/usr/share/man \
    --enable-threads \
    --enable-64bit

make
make -j1 INSTALL_ROOT="$1" install install-private-headers

ln -s "/usr/bin/tclsh${ver1}.${ver2}" "$1/usr/bin/tclsh"
