#!/bin/sh -e

make \
    prefix=/usr \
    sbindir=/usr/bin \
    lib=/usr/lib \
    pkgconfdir=/usr/lib/pkgconfig \
    RAISE_SETFCAP=no \
    DESTDIR="$1" 

make INDENT=true
make DESTDIR="$1" install
