#!/bin/sh -e

export DESTDIR="$1"

mk() {
    cmake -B build \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DJSONCPP_WITH_TESTS=OFF \
        -DJSONCPP_WITH_POST_BUILD_UNITTEST=OFF \
        -DJSONCPP_WITH_CMAKE_PACKAGE=OFF \
        -DJSONCPP_WITH_PKGCONFIG_SUPPORT=OFF \
        "$@"

    cmake --build   build
    cmake --install build
}

mk -DBUILD_SHARED_LIBS=OFF
mk -DBUILD_SHARED_LIBS=ON
