#!/bin/sh -e

# `glibc` uses the `sysinfo` struct defined in `<linux/sysinfo.h>` but `musl`
# uses it's own, leading to redefinition. Just let the linux one be used.
sed -i 's|#include <sys/sysinfo.h>||' common/utils.c

./configure \
    --prefix=/usr \
    --bindir=/usr/bin \
    --disable-documentation \
    --disable-backtrace \
    --disable-zstd

make
make DESTDIR="$1" install
