#!/bin/sh -e

./configure --prefix=/usr \
            --bindir=/bin \
            --libdir=/lib \
            --disable-documentation \
            --disable-backtrace \
            --disable-zstd

make
make DESTDIR="$1" install
