#!/bin/sh -e

./configure \
    --prefix=/usr \
    --sysconfdir=/etc
make

make DESTDIR="$1" install
install -Dm644 conf/bash-completion/completions/mosh \
               "$1/usr/share/bash-completion/completions/mosh"
