#!/bin/sh -e

make

install -Dm 755 sinit "$1/usr/bin/sinit"

install -Dm 755 poweroff "$1/usr/local/bin/poweroff"
install -Dm 755 reboot "$1/usr/local/bin/reboot"

install -Dm 755 rc.boot "$1/lib/sinit/rc.boot"
install -Dm 755 rc.shutdown "$1/lib/sinit/rc.shutdown"

cat <<EOF

NOTE: This package is installed as /usr/bin/sinit
Please update your kernel parameters accordingly,

e.g. init=/usr/bin/sinit

Also keep in mind that sinit does not use /etc/inittab
The default busybox runit service supervisor will still be initialized.

The 'poweroff' and 'reboot' commands are located in /usr/local/bin
You may want to modify your 'PATH' to include this directory at the front.

Or you may opt to use alias functions,

poweroff () { /bin/kill -s USR1 1 ; }
reboot () { /bin/kill -s INT 1 ; }

EOF
