#!/bin/sh -e

# be explicitly static for pid 1
make CFLAGS="$CFLAGS -static"

# /usr/bin
install -Dm 755 sinit "$1/usr/bin/sinit"

# /etc
install -Dm 755 sinit.conf "$1/etc/sinit.conf"
mkdir -p /etc/sinit.d

# /lib/sinit
install -Dm 755 rc.boot "$1/lib/sinit/rc.boot"
install -Dm 755 rc.shutdown "$1/lib/sinit/rc.shutdown"
