#!/bin/sh -e

grep -q SINIT_ /etc/rc.conf || cat <<EOF >> /etc/rc.conf

# Uncomment these to run the scripts for sinit
# SINIT_SHUTDOWN_HOOKS=1
# SINIT_ENABLE_GETTY=1
# SINIT_ENABLE_RUNIT=1
EOF

cat <<EOF

IMPORTANT: 
        If you want to start using sinit, you 
	need to edit your /etc/rc.conf to enable
	SINIT variables. 

	Init is installed to /usr/bin/sinit, you 
	can also link it to /usr/bin/init but you 
	should only do that on a chroot environment.

	To completely replace busybox init programs,
	you can do (while chrooted)

	    kiss a | grep ^sinit | kiss a -

	This should replace,

	* /usr/bin/init
	* /usr/bin/halt
	* /usr/bin/poweroff
	* /usr/bin/reboot
	* /usr/bin/respawn (if ubase is installed)

EOF
