#!/bin/sh -e

cat <<EOF

NOTE:
        This package is installed as /usr/bin/sinit
        Please update your kernel parameters
        accordingly,

        -> init=/bin/sinit

        Please keep in mind that sinit does not use
        the /etc/inittab file. The default busybox
        runit service supervisor will still be
        initialized. To use a different supervisor,
        edit /etc/sinit.conf and place script(s) in
        the /etc/sinit.d/ directory suffixed with
        *.sh

        To shutdown:

        -> # kill -s USR1 1

        Advanced users may place in /etc/sinit.d/
        a "rc.shutdown" file which will be sourced
        instead of /lib/init/rc.shutdown

        To reboot:

        -> # kill -s INT 1

        You may opt to install the above commands
        as scripts in /usr/local/bin and modify it
        to the front of 'PATH'.

        In the future this [lack of poweroff and
        reboot scripts in /bin] may change if kiss
        gains slotting abilities or if busybox
        becomes optional. Another possibility is
        a suckless overlay with a forked busybox.

EOF
