#!/bin/sh -e

cat <<EOF

IMPORTANT: 
        If you want to start using sinit, you 
	need to edit your /etc/rc.conf to add
	SINIT variables. 

	These variables are,

	    [1mSINIT_SHUTDOWN_HOOKS=1[m (Mandatory)
	    [1mSINIT_ENABLE_GETTY=1[m   (Mandatory)
	    [1mSINIT_ENABLE_RUNIT=1[m   (Optional)

	Init is installed to /usr/bin/sinit, you 
	can also link it to /usr/bin/init but you 
	should only do that on a chroot environment.

	To completely replace busybox init programs,
	you can do (while chrooted)

	    kiss a | grep ^sinit | kiss a -

	This should replace,

	* /usr/bin/init
	* /usr/bin/halt
	* /usr/bin/poweroff
	* /usr/bin/reboot

EOF
