#!/bin/sh -e

rm -f intel-ucode/list intel-ucode-with-caveats/list
mkdir -p kernel/x86/microcode
iucode_tool -w kernel/x86/microcode/GenuineIntel.bin \
            intel-ucode/ intel-ucode-with-caveats/
echo kernel/x86/microcode/GenuineIntel.bin | \
    cpio -o -H newc -R 0:0 > intel-ucode.img

install -D -m0644 intel-ucode.img "$1/boot/intel-ucode.img"
