#!/bin/sh
cat <<EOF
NOTE: OpenNTPD needs its own user and group for privilege separation.
      Please create the needed users by using these commands in
      succession:

  # addgroup -S openntpd
  # adduser -S -h /var/empty -G openntpd openntpd
EOF
