Remove dependency on bsd make extension.

--- a/Makefile
+++ b/Makefile
@@ -23,7 +23,7 @@
 $(PROG): $(OBJS)
 	$(CC) $(OBJS) $(LDPATH) $(LIBS) -o $@
 
-$(OBJS): *.o: *.c
+.c.o:
 	$(CC) $(CFLAGS) $(INCLUDES) -c $< -o $@
 
 install: all
