#!/bin/sh -e

python3 setup.py build

cmake -B build \
    -DCMAKE_BUILD_TYPE=None \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DUSE_PYTHON_INCLUDE_DIR=FALSE

cmake --build build
python3 setup.py install \
    --prefix=/usr \
    --root="$1" \
    --skip-build \
    --install-headers=/usr/include/pybind11
DESTDIR="$1" cmake --install build

mkdir -p "$1/usr/lib"
mv "$1/usr/share/cmake" "$1/usr/lib"
