#!/bin/sh -e

export DESTDIR="$1"

export LD_LIBRARY_PATH="/usr/lib/llvm/roc/lib:$LD_LIBRARY_PATH"

cmake -B build -S lib/comgr \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_BUILD_TYPE=Release \
    -DLLD_DIR=/usr/lib/llvm/roc/lib/cmake/lld \
    -DLLVM_DIR=/usr/lib/llvm/roc/lib/cmake/llvm \
    -DClang_DIR=/usr/lib/llvm/roc/lib/cmake/clang

cmake --build   build
cmake --install build
