#!/bin/sh

cat <<EOF

### IMPORTANT ###
### IMPORTANT ###

Note: For bookmarks install "pandoc-bin".
      In $HOME/.config/wyeb./main.conf
      change "generator=" to "generator=pandoc -f markdown -t html %s".

### IMPORTANT ###
### IMPORTANT ###

EOF
