#!/bin/sh -e

for py in py-attrs py-jinja py-markupsafe py-pygments py-pypeg py-yaml; do (
    cd "$py"

    python3 setup.py build
    python3 setup.py install --prefix=/usr --root="$1"
) done

python3 setup.py build
python3 setup.py install --prefix=/usr --root="$1"
