#!/bin/sh -e

# Remove libtool dependency.
sed -i 's/as_fn_error.*libtool/: "/g' configure

./configure \
    --prefix=/usr \
    --sbindir=/usr/bin

make
make DESTDIR="$1" install

# Why are tests installed to $DESTDIR's /tmp ?
rm -rf "$1/tmp"
