#!/bin/sh -e

printf "NOTE: It is HIGHLY recommended to build this package with sane build flags and 'ccache' enabled!\n"

kiss list musl && {
    for patch in musl-*.patch; do
        patch -p1 < "$patch"
    done
}

# Saves me from having to duplicate this package in 'gcommunity' just for 2 patches.
kiss list glibc && {
    for patch in glibc-*.patch; do
        patch -p1 < "$patch"
    done
}

# Glob includes the GCC patchset aswell.
for patch in chromium-*.patch; do
    patch -p1 < "$patch"
done

( cd ungoogled-chromium; patch -p1 < ../ungoogled-patchset-89.0.4389.40.patch )

python3 ungoogled-chromium/utils/prune_binaries.py \
    ./ ungoogled-chromium/pruning.list

# Bypass the Python script and apply patches ourselves to avoid GNU patch.
while read -r patch; do
    patch -p1 < "ungoogled-chromium/patches/$patch"
done < ungoogled-chromium/patches/series

python3 ungoogled-chromium/utils/domain_substitution.py apply \
    -r ungoogled-chromium/domain_regex.list \
    -f ungoogled-chromium/domain_substitution.list \
    -c domainsubcache.tar.gz ./

# Avoid falling back to preprocessor mode when sources contain time macros.
kiss list ccache && export CCACHE_SLOPPINESS=time_macros

# Force script incompatible with Python 3 to use /usr/bin/python2.
sed -i "1s|python$|&2|" third_party/dom_distiller_js/protoc_plugins/*.py

mkdir -p third_party/node/linux/node-linux-x64/bin
ln -s /usr/bin/node third_party/node/linux/node-linux-x64/bin/

export CC="${CC:-cc}"
export CXX="${CXX:-c++}"
export AR="${AR:-ar}"
export NM="${NM:-nm}"

# 'clang' builds are untested but should most likely work fine with our flags.
case $("$CC" --version) in (*clang*)
    clang=true
esac

# compile gn early, so it can be used to generate gni stuff.
python2 tools/gn/bootstrap/bootstrap.py --skip-generate-buildfiles

# libevent: Random freezes with javascript.
# libpng: KISS builds with APNG patch (https://crbug.com/752403#c10).
# zlib: KISS builds without minizip.
system="
    ffmpeg
    flac
    fontconfig
    freetype
    harfbuzz-ng
    libdrm
    libjpeg
    libwebp
    opus
"

# remove build scripts for system provided dependencies - basically does the
# same as the bundled script to remove bundled libs, but this way we don't
# have to list the remaining libs.
for LIB in "$system" libjpeg_turbo; do
    find . -type f -path "*third_party/$LIB/*" \
        \! -path "*third_party/$LIB/chromium/*" \
        \! -path "*third_party/$LIB/google/*" \
        \! -path './base/third_party/icu/*' \
        \! -path './third_party/pdfium/third_party/freetype/include/pstables.h' \
        \! -path './third_party/harfbuzz-ng/utils/hb_scoped.h' \
        \! -name '*.gn' \
        \! -name '*.gni' \
        \! -name '*.isolate' \
        \! -name '*.py' \
        -exec rm -rf {} +
done

# switch to system provided dependencies.
# shellcheck disable=2086
python2 build/linux/unbundle/replace_gn_files.py --system-libraries $system

python2 third_party/libaddressinput/chromium/tools/update-strings.py

kiss list libva && vaapi=true

conf="
    angle_enable_vulkan=false
    blink_symbol_level=0
    build_dawn_tests=false
    custom_toolchain=\"//build/toolchain/linux/unbundle:default\"
    dawn_enable_vulkan=false
    enable_perfetto_unittests=false
    enable_swiftshader_vulkan=false
    enable_vr=false
    enable_widevine=false
    fatal_linker_warnings=false
    ffmpeg_branding=\"Chrome\"
    host_toolchain=\"//build/toolchain/linux/unbundle:default\"
    is_cfi=false
    is_clang=${clang:-false}
    is_debug=false
    is_unsafe_developer_build=false
    link_pulseaudio=false
    ozone_platform_wayland=false
    proprietary_codecs=true
    rtc_use_pipewire=false
    symbol_level=0
    use_allocator=\"none\"
    use_allocator_shim=false
    use_atk=false
    use_cups=false
    use_custom_libcxx=false
    use_dbus=false
    use_gnome_keyring=false
    use_gold=false
    use_kerberos=false
    use_libpci=false
    use_lld=false
    use_pulseaudio=false
    use_sysroot=false
    use_system_harfbuzz=true
    use_vaapi=${vaapi:-false}
    use_x11=true
    use_xkbcommon=false
    chrome_pgo_phase=0
    enable_hangout_services_extension=false
    enable_js_type_check=false
    enable_mdns=false
    enable_mse_mpeg2ts_stream_parser=true
    enable_nacl=false
    enable_nacl_nonsfi=false
    enable_one_click_signin=false
    enable_reading_list=false
    enable_remoting=false
    enable_reporting=false
    enable_service_discovery=false
    exclude_unwind_tables=true
    fieldtrial_testing_like_official_build=true
    google_api_key=\"\"
    google_default_client_id=\"\"
    google_default_client_secret=\"\"
    safe_browsing_mode=0
    treat_warnings_as_errors=false
    use_official_google_api_keys=false
    use_unofficial_version_number=false
"

out/Release/gn gen out/Release --args="$conf" --script-executable=python2

# final link needs lots of file descriptors, almost all shells support the -n flag.
# shellcheck disable=2039
ulimit -n 4096

ninja -C out/Release chrome

# Package the monster.
install -Dm755 chromium.sh            "$1/usr/bin/chromium"
install -Dm755 out/Release/chrome     "$1/usr/lib/chromium/chromium"
install -Dm644 out/Release/icudtl.dat "$1/usr/lib/chromium"
install -Dm644 out/Release/locales/*.pak    -t "$1/usr/lib/chromium/locales"
install -Dm755 out/Release/swiftshader/*.so -t "$1/usr/lib/chromium/swiftshader"

for lib in libEGL.so libGLESv2.so; do
    install -Dm755 "out/Release/$lib" "$1/usr/lib/chromium"
done

for stuff in bin pak; do
    install -Dm644 out/Release/*.$stuff "$1/usr/lib/chromium"
done
