#!/bin/sh -e

export DESTDIR="$1"

for patch in *.patch; do
    patch -p1 < "$patch"
done

# Get rid of i18n.
rm -rf po poqm

# Fix missing include in Qt 5.14.
sed -i 's/\(Settings>\)/\1\n#include <QFile>/' \
    src/plugins/VerticalTabs/verticaltabsplugin.cpp

# Fix a build problem caused by Qt 5.15
sed -i '/#include <QPainter>/a #include <QPainterPath>' \
    src/lib/tools/qztools.cpp

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR=/usr/lib \
    -DCMAKE_BUILD_TYPE=Release \
    -DBUILD_TESTING=OFF \
    -DDISABLE_DBUS=ON

cmake --build   build
cmake --install build

install -Dm755 falkon-privacy "$1/usr/bin/falkon-privacy"
