#!/bin/sh -e

# We don't need to expand expression in quotes.
# shellcheck disable=2016
sed -i '/pkgconfig_DATA/i pkgconfigdir=$(libdir)/pkgconfig' Makefile.am

./bootstrap.sh
./configure --prefix=/usr

make
make DESTDIR="$1" install
install -Dm644 fts.3 "$1/usr/share/man/man3/musl-fts.3"
