#!/bin/sh -e

cd dnscrypt-proxy

go build \
    -mod=vendor \
    -trimpath

install -Dm755 dnscrypt-proxy "$1/usr/bin/dnscrypt-proxy"
install -Dm644 example-dnscrypt-proxy.toml "$1/etc/dnscrypt-proxy/dnscrypt-proxy.toml"

for config in *.txt; do
    install -Dm644 "$config" "$1/etc/dnscrypt-proxy/${config#example-}"
done

install -Dm755 ../dnscrypt-proxy.run      "$1/etc/sv/dnscrypt-proxy/run"
ln -s /run/runit/supervise.dnscrypt-proxy "$1/etc/sv/dnscrypt-proxy/supervise"
