#!/bin/sh -e

export DESTDIR="$1"

meson \
    --prefix=/usr \
    -Dbuildtype=release \
    -Ddbghelp=disabled \
    -Dintrospection=disabled \
    -Dexample=false \
    -Dgtk_doc=disabled \
    . output

ninja -C output
ninja -C output install
