#!/bin/sh -e

./configure \
    --prefix=/usr \
    --disable-nls \
    --disable-metalink \
    --disable-websocket \
    --disable-epoll \
    --without-sqlite3

make
make DESTDIR="$1" install

# Remove docs.
rm -rf "$1/usr/share/doc"
rm -rf "$1/usr/share/man/ru"
rm -rf "$1/usr/share/man/pt"
