#!/bin/sh -e

./configure \
	--prefix=/usr \
	--bindir=/usr/bin \
	--sbindir=/usr/bin \
	--datarootdir=/usr/share \
	--disable-example \
	MOUNT_FUSE_PATH=/usr/bin \
	UDEV_RULES_PATH=/usr/lib/udev

make
make DESTDIR="$1" install
