#!/bin/sh -e

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    --with-perl=module \
    --with-otr=no \
    --with-proxy \
    --enable-true-color

make
make DESTDIR="$1" install
