#!/bin/sh -e

export DESTDIR="$1"

cmake -B build \
	-DCMAKE_INSTALL_PREFIX=/usr \
	-DCMAKE_INSTALL_LIBDIR=/usr/lib \
	-DINSTALL_UDEV_RULES=ON \
	-DCMAKE_BUILD_TYPE=Release

cmake --build   build
cmake --install build

