#!/bin/sh -e

# Disable check for TTF font. 
sed -i 's/as_fn_error.*font file/: "/' configure

./configure  \
    --prefix=/usr \
    --sbindir=/usr/bin \
    --sysconfdir=/etc \
    --without-php \
    --disable-avahi \
    --disable-mutool \
    --disable-dbus \
    --disable-braille \
    --without-rcdir 
	
make
make DESTDIR="$1" install
