#!/bin/sh -e

./configure \
    --prefix=/usr \
    --with-modules \
    --without-all \
    --without-x \
    --with-x-toolkit=no \
    --with-x=no \
    --with-gnutls=yes \
    --with-xml2=yes

mkdir -p "$1/usr/share/emacs/site-lisp"
cat << EOF > "$1/usr/share/emacs/site-lisp/site-start.el"
;; Better security defaults
(with-eval-after-load 'gnutls
  (setq
   gnutls-verify-error t
   gnutls-min-prime-bits 2048
   gnutls-trustfiles '("/etc/ssl/cert.pem")))
EOF

make
make DESTDIR="$1" install

rm -rf "$1/usr/lib/systemd"
