#!/bin/sh -e

# prepend environment to config.mk defs
sed -i config.mk \
    -e "/^CFLAGS/s/=/= $CFLAGS -static/" \
    -e "/^LDFLAGS/s/=/= $LDFLAGS -static/"

make sbase-box
make DESTDIR="$1" PREFIX=/usr sbase-box-install

# Remove 'tar'/'sed' which won't work with kiss.
unlink "$1/usr/bin/tar"
unlink "$1/usr/bin/sed"
