#!/bin/sh -e

make \
    LIBDIR=lib \
    INCLUDEDIR=include \
    PREFIX=/usr \
    TARGET=gtk3 \
    NETSURF_GTK_MAJOR=3

make \
    LIBDIR=lib \
    INCLUDEDIR=include \
    PREFIX=/usr \
    DESTDIR="$1" \
    install
