#!/bin/sh -e

make \
    LIBDIR=lib \
    INCLUDEDIR=include \
    PREFIX=/usr \
    NETSURF_GTK_MAJOR=3 \
    TARGET=gtk

make \
    LIBDIR=lib \
    INCLUDEDIR=include \
    PREFIX=/usr \
    NETSURF_GTK_MAJOR=3 \
    TARGET=gtk \
    DESTDIR="$1" \
    install

ln -s /usr/bin/netsurf-gtk3 "$1/usr/bin/netsurf"
