#!/bin/sh

export DESTDIR="$1"

cmake -B build \
    -DRELEASE=ON \
    -DCMAKE_BUILD_TYPE=None \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DBUILD_I18N=OFF \
    -DCURSES_NEED_WIDE=ON \
    -DCURSES_INCLUDE_PATH=/usr/include

cmake --build   build
cmake --install build
