#!/bin/sh -e

patch -p1 < 0001-make-iproute2-fhs-compliant.patch
sh

./configure

make
make DESTDIR="$1" SBINDIR="/usr/bin" install

install -Dm0644 include/libnetlink.h "$1/usr/include/libnetlink.h"
install -Dm0644 lib/libnetlink.a "$1/usr/lib/libnetlink.a"
