#!/bin/sh -e

mk() {
    make \
        CC="${CC:-cc}" \
        OPT="$CFLAGS -fPIC" \
        ZLIB=yes \
        PREFIX=/usr \
        SBINDIR=/usr/bin \
        SHAREDIR=/usr/share/hwdata \
        "$@"
}

mk SHARED=yes
mk SHARED=yes DESTDIR="$1" install

mk -B
install -Dm644 lib/libpci.a "$1/usr/lib/libpci.a"
