#!/bin/sh -e

mk() {
    make \
        CC="${CC:-cc}" \
        OPT="$CFLAGS -fPIC" \
        ZLIB=yes \
        PREFIX=/usr \
        SBINDIR=/usr/bin \
        SHAREDIR=/usr/share/hwdata \
        "$@"
}

mk
mk DESTDIR="$1" install install-lib
