#!/bin/sh -e

# Remove startup-notification dependency.
sed -i'' 's/as_fn_error.*up-no.*/: "/' configure
sed -i'' '/LIBSN/d' Makefile.in
patch -p1 < i3-no-libsn.patch

./configure \
    --prefix=/usr \
    --disable-docs \
    --disable-builddir

make
make DESTDIR="$1" install
