#!/bin/sh -e

export DESTDIR="$1"

# Use local glm headers.
sed -i 's|<glm/glm\.hpp>|"../glm/glm/glm.hpp"|' src/*.?pp

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_BUILD_TYPE=Release

cmake --build   build
cmake --install build
