#!/bin/sh -e

./configure \
    --disable-pinentry-qt \
    --disable-pinentry-gtk2 \
    --disable-inside-emacs \
    --disable-pinentry-emacs \
    --disable-pinentry-curses \
    --enable-pinentry-tty

make
make DESTDIR="$1" install
