#!/bin/sh -e

cmake . \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR=/usr/lib \
    -DENABLE_UNSTABLE_API_ABI_HEADERS=OFF \
    -DENABLE_UTILS=OFF \
    -DENABLE_CPP=OFF \
    -DENABLE_QT5=OFF \
    -DENABLE_CMS=lcms2 \
    -DENABLE_LIBOPENJPEG=none \
    -DWITH_NSS3=OFF

make
make DESTDIR="$1" install
