#!/bin/sh -e

# give option to easily enable nftables by passing USE="--with-nftables" to kiss
[ -z "$USE" ] && USE="--disable-nftables"

autoreconf -i

./configure --prefix=/usr \
            --sbindir=/usr/sbin \
            --enable-libipq --with-xtlibdir=/lib/xtables "$USE"

make

make DESTDIR="$1" install
