#!/bin/sh -e

# Fix build with GCC 10.
export CFLAGS="$CFLAGS -fcommon"

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --enable-cgroup \
    --enable-unicode \
    --enable-taskstats

make
make DESTDIR="$1" install
